# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReceiptsAndMore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReceiptsAndMore
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  
  target 'ReceiptsAndMoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReceiptsAndMoreUITests' do
    # Pods for testing
  end

end
